FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["./es-poc.csproj", "."]
RUN dotnet restore "./es-poc.csproj"
COPY . .
RUN dotnet build "es-poc.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "es-poc.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "es-poc.dll"]